// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dynamic_update_interface.proto

package client

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddZoneRequest struct {
	Zone                 string   `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	ZoneContent          string   `protobuf:"bytes,2,opt,name=zone_content,json=zoneContent,proto3" json:"zone_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddZoneRequest) Reset()         { *m = AddZoneRequest{} }
func (m *AddZoneRequest) String() string { return proto.CompactTextString(m) }
func (*AddZoneRequest) ProtoMessage()    {}
func (*AddZoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_def07e43856809cb, []int{0}
}

func (m *AddZoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddZoneRequest.Unmarshal(m, b)
}
func (m *AddZoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddZoneRequest.Marshal(b, m, deterministic)
}
func (m *AddZoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddZoneRequest.Merge(m, src)
}
func (m *AddZoneRequest) XXX_Size() int {
	return xxx_messageInfo_AddZoneRequest.Size(m)
}
func (m *AddZoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddZoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddZoneRequest proto.InternalMessageInfo

func (m *AddZoneRequest) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *AddZoneRequest) GetZoneContent() string {
	if m != nil {
		return m.ZoneContent
	}
	return ""
}

type AddZoneResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddZoneResponse) Reset()         { *m = AddZoneResponse{} }
func (m *AddZoneResponse) String() string { return proto.CompactTextString(m) }
func (*AddZoneResponse) ProtoMessage()    {}
func (*AddZoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_def07e43856809cb, []int{1}
}

func (m *AddZoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddZoneResponse.Unmarshal(m, b)
}
func (m *AddZoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddZoneResponse.Marshal(b, m, deterministic)
}
func (m *AddZoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddZoneResponse.Merge(m, src)
}
func (m *AddZoneResponse) XXX_Size() int {
	return xxx_messageInfo_AddZoneResponse.Size(m)
}
func (m *AddZoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddZoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddZoneResponse proto.InternalMessageInfo

type DeleteZoneRequest struct {
	Zones                []string `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteZoneRequest) Reset()         { *m = DeleteZoneRequest{} }
func (m *DeleteZoneRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteZoneRequest) ProtoMessage()    {}
func (*DeleteZoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_def07e43856809cb, []int{2}
}

func (m *DeleteZoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteZoneRequest.Unmarshal(m, b)
}
func (m *DeleteZoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteZoneRequest.Marshal(b, m, deterministic)
}
func (m *DeleteZoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteZoneRequest.Merge(m, src)
}
func (m *DeleteZoneRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteZoneRequest.Size(m)
}
func (m *DeleteZoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteZoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteZoneRequest proto.InternalMessageInfo

func (m *DeleteZoneRequest) GetZones() []string {
	if m != nil {
		return m.Zones
	}
	return nil
}

type DeleteZoneResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteZoneResponse) Reset()         { *m = DeleteZoneResponse{} }
func (m *DeleteZoneResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteZoneResponse) ProtoMessage()    {}
func (*DeleteZoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_def07e43856809cb, []int{3}
}

func (m *DeleteZoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteZoneResponse.Unmarshal(m, b)
}
func (m *DeleteZoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteZoneResponse.Marshal(b, m, deterministic)
}
func (m *DeleteZoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteZoneResponse.Merge(m, src)
}
func (m *DeleteZoneResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteZoneResponse.Size(m)
}
func (m *DeleteZoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteZoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteZoneResponse proto.InternalMessageInfo

type AddRRsetRequest struct {
	Zone                 string   `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	Rrsets               []*RRset `protobuf:"bytes,2,rep,name=rrsets,proto3" json:"rrsets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRRsetRequest) Reset()         { *m = AddRRsetRequest{} }
func (m *AddRRsetRequest) String() string { return proto.CompactTextString(m) }
func (*AddRRsetRequest) ProtoMessage()    {}
func (*AddRRsetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_def07e43856809cb, []int{4}
}

func (m *AddRRsetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRRsetRequest.Unmarshal(m, b)
}
func (m *AddRRsetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRRsetRequest.Marshal(b, m, deterministic)
}
func (m *AddRRsetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRRsetRequest.Merge(m, src)
}
func (m *AddRRsetRequest) XXX_Size() int {
	return xxx_messageInfo_AddRRsetRequest.Size(m)
}
func (m *AddRRsetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRRsetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRRsetRequest proto.InternalMessageInfo

func (m *AddRRsetRequest) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *AddRRsetRequest) GetRrsets() []*RRset {
	if m != nil {
		return m.Rrsets
	}
	return nil
}

type AddRRsetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRRsetResponse) Reset()         { *m = AddRRsetResponse{} }
func (m *AddRRsetResponse) String() string { return proto.CompactTextString(m) }
func (*AddRRsetResponse) ProtoMessage()    {}
func (*AddRRsetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_def07e43856809cb, []int{5}
}

func (m *AddRRsetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRRsetResponse.Unmarshal(m, b)
}
func (m *AddRRsetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRRsetResponse.Marshal(b, m, deterministic)
}
func (m *AddRRsetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRRsetResponse.Merge(m, src)
}
func (m *AddRRsetResponse) XXX_Size() int {
	return xxx_messageInfo_AddRRsetResponse.Size(m)
}
func (m *AddRRsetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRRsetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddRRsetResponse proto.InternalMessageInfo

type DeleteDomainRequest struct {
	Zone                 string   `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	Names                []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDomainRequest) Reset()         { *m = DeleteDomainRequest{} }
func (m *DeleteDomainRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDomainRequest) ProtoMessage()    {}
func (*DeleteDomainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_def07e43856809cb, []int{6}
}

func (m *DeleteDomainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDomainRequest.Unmarshal(m, b)
}
func (m *DeleteDomainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDomainRequest.Marshal(b, m, deterministic)
}
func (m *DeleteDomainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDomainRequest.Merge(m, src)
}
func (m *DeleteDomainRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDomainRequest.Size(m)
}
func (m *DeleteDomainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDomainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDomainRequest proto.InternalMessageInfo

func (m *DeleteDomainRequest) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *DeleteDomainRequest) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type DeleteDomainResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDomainResponse) Reset()         { *m = DeleteDomainResponse{} }
func (m *DeleteDomainResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteDomainResponse) ProtoMessage()    {}
func (*DeleteDomainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_def07e43856809cb, []int{7}
}

func (m *DeleteDomainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDomainResponse.Unmarshal(m, b)
}
func (m *DeleteDomainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDomainResponse.Marshal(b, m, deterministic)
}
func (m *DeleteDomainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDomainResponse.Merge(m, src)
}
func (m *DeleteDomainResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteDomainResponse.Size(m)
}
func (m *DeleteDomainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDomainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDomainResponse proto.InternalMessageInfo

type DeleteRRsetRequest struct {
	Zone                 string         `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	Rrsets               []*RRsetHeader `protobuf:"bytes,2,rep,name=rrsets,proto3" json:"rrsets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeleteRRsetRequest) Reset()         { *m = DeleteRRsetRequest{} }
func (m *DeleteRRsetRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRRsetRequest) ProtoMessage()    {}
func (*DeleteRRsetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_def07e43856809cb, []int{8}
}

func (m *DeleteRRsetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRRsetRequest.Unmarshal(m, b)
}
func (m *DeleteRRsetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRRsetRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRRsetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRRsetRequest.Merge(m, src)
}
func (m *DeleteRRsetRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRRsetRequest.Size(m)
}
func (m *DeleteRRsetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRRsetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRRsetRequest proto.InternalMessageInfo

func (m *DeleteRRsetRequest) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *DeleteRRsetRequest) GetRrsets() []*RRsetHeader {
	if m != nil {
		return m.Rrsets
	}
	return nil
}

type DeleteRRsetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRRsetResponse) Reset()         { *m = DeleteRRsetResponse{} }
func (m *DeleteRRsetResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRRsetResponse) ProtoMessage()    {}
func (*DeleteRRsetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_def07e43856809cb, []int{9}
}

func (m *DeleteRRsetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRRsetResponse.Unmarshal(m, b)
}
func (m *DeleteRRsetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRRsetResponse.Marshal(b, m, deterministic)
}
func (m *DeleteRRsetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRRsetResponse.Merge(m, src)
}
func (m *DeleteRRsetResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRRsetResponse.Size(m)
}
func (m *DeleteRRsetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRRsetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRRsetResponse proto.InternalMessageInfo

type DeleteRdataRequest struct {
	Zone                 string   `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	Rrsets               []*RRset `protobuf:"bytes,2,rep,name=rrsets,proto3" json:"rrsets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRdataRequest) Reset()         { *m = DeleteRdataRequest{} }
func (m *DeleteRdataRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRdataRequest) ProtoMessage()    {}
func (*DeleteRdataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_def07e43856809cb, []int{10}
}

func (m *DeleteRdataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRdataRequest.Unmarshal(m, b)
}
func (m *DeleteRdataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRdataRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRdataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRdataRequest.Merge(m, src)
}
func (m *DeleteRdataRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRdataRequest.Size(m)
}
func (m *DeleteRdataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRdataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRdataRequest proto.InternalMessageInfo

func (m *DeleteRdataRequest) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *DeleteRdataRequest) GetRrsets() []*RRset {
	if m != nil {
		return m.Rrsets
	}
	return nil
}

type DeleteRdataResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRdataResponse) Reset()         { *m = DeleteRdataResponse{} }
func (m *DeleteRdataResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRdataResponse) ProtoMessage()    {}
func (*DeleteRdataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_def07e43856809cb, []int{11}
}

func (m *DeleteRdataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRdataResponse.Unmarshal(m, b)
}
func (m *DeleteRdataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRdataResponse.Marshal(b, m, deterministic)
}
func (m *DeleteRdataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRdataResponse.Merge(m, src)
}
func (m *DeleteRdataResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRdataResponse.Size(m)
}
func (m *DeleteRdataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRdataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRdataResponse proto.InternalMessageInfo

type UpdateRdataRequest struct {
	Zone                 string   `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	OldRrset             *RRset   `protobuf:"bytes,2,opt,name=old_rrset,json=oldRrset,proto3" json:"old_rrset,omitempty"`
	NewRrset             *RRset   `protobuf:"bytes,3,opt,name=new_rrset,json=newRrset,proto3" json:"new_rrset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRdataRequest) Reset()         { *m = UpdateRdataRequest{} }
func (m *UpdateRdataRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRdataRequest) ProtoMessage()    {}
func (*UpdateRdataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_def07e43856809cb, []int{12}
}

func (m *UpdateRdataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRdataRequest.Unmarshal(m, b)
}
func (m *UpdateRdataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRdataRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRdataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRdataRequest.Merge(m, src)
}
func (m *UpdateRdataRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRdataRequest.Size(m)
}
func (m *UpdateRdataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRdataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRdataRequest proto.InternalMessageInfo

func (m *UpdateRdataRequest) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *UpdateRdataRequest) GetOldRrset() *RRset {
	if m != nil {
		return m.OldRrset
	}
	return nil
}

func (m *UpdateRdataRequest) GetNewRrset() *RRset {
	if m != nil {
		return m.NewRrset
	}
	return nil
}

type UpdateRdataResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRdataResponse) Reset()         { *m = UpdateRdataResponse{} }
func (m *UpdateRdataResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRdataResponse) ProtoMessage()    {}
func (*UpdateRdataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_def07e43856809cb, []int{13}
}

func (m *UpdateRdataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRdataResponse.Unmarshal(m, b)
}
func (m *UpdateRdataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRdataResponse.Marshal(b, m, deterministic)
}
func (m *UpdateRdataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRdataResponse.Merge(m, src)
}
func (m *UpdateRdataResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRdataResponse.Size(m)
}
func (m *UpdateRdataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRdataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRdataResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AddZoneRequest)(nil), "client.AddZoneRequest")
	proto.RegisterType((*AddZoneResponse)(nil), "client.AddZoneResponse")
	proto.RegisterType((*DeleteZoneRequest)(nil), "client.DeleteZoneRequest")
	proto.RegisterType((*DeleteZoneResponse)(nil), "client.DeleteZoneResponse")
	proto.RegisterType((*AddRRsetRequest)(nil), "client.AddRRsetRequest")
	proto.RegisterType((*AddRRsetResponse)(nil), "client.AddRRsetResponse")
	proto.RegisterType((*DeleteDomainRequest)(nil), "client.DeleteDomainRequest")
	proto.RegisterType((*DeleteDomainResponse)(nil), "client.DeleteDomainResponse")
	proto.RegisterType((*DeleteRRsetRequest)(nil), "client.DeleteRRsetRequest")
	proto.RegisterType((*DeleteRRsetResponse)(nil), "client.DeleteRRsetResponse")
	proto.RegisterType((*DeleteRdataRequest)(nil), "client.DeleteRdataRequest")
	proto.RegisterType((*DeleteRdataResponse)(nil), "client.DeleteRdataResponse")
	proto.RegisterType((*UpdateRdataRequest)(nil), "client.UpdateRdataRequest")
	proto.RegisterType((*UpdateRdataResponse)(nil), "client.UpdateRdataResponse")
}

func init() { proto.RegisterFile("dynamic_update_interface.proto", fileDescriptor_def07e43856809cb) }

var fileDescriptor_def07e43856809cb = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x4f, 0x6b, 0xd4, 0x40,
	0x18, 0xc6, 0x9b, 0x6e, 0xbb, 0x36, 0x6f, 0xea, 0x9f, 0x4e, 0xe3, 0x1a, 0x53, 0x91, 0x35, 0x20,
	0xac, 0x0a, 0x7b, 0xa8, 0x57, 0xa1, 0x88, 0x2b, 0x56, 0x14, 0x84, 0x40, 0x2f, 0x5e, 0xc2, 0x98,
	0x79, 0x85, 0x40, 0x76, 0x66, 0x4d, 0xa6, 0x14, 0x3d, 0x79, 0xf5, 0x5b, 0x4b, 0x66, 0x26, 0xc9,
	0x4c, 0x13, 0x76, 0x2f, 0x3d, 0xed, 0x66, 0x9e, 0x37, 0xbf, 0xe7, 0x79, 0x77, 0x1e, 0x16, 0x9e,
	0xb3, 0xdf, 0x9c, 0xae, 0x8b, 0x3c, 0xbb, 0xde, 0x30, 0x2a, 0x31, 0x2b, 0xb8, 0xc4, 0xea, 0x27,
	0xcd, 0x71, 0xb9, 0xa9, 0x84, 0x14, 0x64, 0x9a, 0x97, 0x05, 0x72, 0x19, 0x07, 0x55, 0x55, 0xa3,
	0xd4, 0x87, 0xc9, 0x27, 0x78, 0xf0, 0x9e, 0xb1, 0xef, 0x82, 0x63, 0x8a, 0xbf, 0xae, 0xb1, 0x96,
	0x84, 0xc0, 0xc1, 0x1f, 0xc1, 0x31, 0xf2, 0xe6, 0xde, 0xc2, 0x4f, 0xd5, 0x77, 0xf2, 0x02, 0x8e,
	0x9b, 0xcf, 0x2c, 0x17, 0x5c, 0x22, 0x97, 0xd1, 0xbe, 0xd2, 0x82, 0xe6, 0xec, 0x83, 0x3e, 0x4a,
	0x4e, 0xe0, 0x61, 0x07, 0xaa, 0x37, 0x82, 0xd7, 0x98, 0xbc, 0x82, 0x93, 0x15, 0x96, 0x28, 0xd1,
	0xc6, 0x87, 0x70, 0xd8, 0xbc, 0x56, 0x47, 0xde, 0x7c, 0xb2, 0xf0, 0x53, 0xfd, 0x90, 0x84, 0x40,
	0xec, 0x51, 0x03, 0xf8, 0xaa, 0x98, 0x69, 0x5a, 0xa3, 0xdc, 0x96, 0xee, 0x25, 0x4c, 0xd5, 0x4a,
	0x75, 0xb4, 0x3f, 0x9f, 0x2c, 0x82, 0xf3, 0xfb, 0x4b, 0xbd, 0xe9, 0x52, 0xbf, 0x69, 0xc4, 0x84,
	0xc0, 0xa3, 0x9e, 0x66, 0x1c, 0x2e, 0xe0, 0x54, 0xfb, 0xae, 0xc4, 0x9a, 0x16, 0x7c, 0x9b, 0x4b,
	0x08, 0x87, 0x9c, 0xae, 0x51, 0x9b, 0xf8, 0xa9, 0x7e, 0x48, 0x66, 0x10, 0xba, 0x00, 0x03, 0xbe,
	0x6a, 0x17, 0xda, 0x99, 0xfe, 0xcd, 0xad, 0xf4, 0xa7, 0x4e, 0xfa, 0x4b, 0xa4, 0x0c, 0xab, 0x6e,
	0x87, 0xc7, 0x6d, 0x5e, 0x77, 0x8d, 0x6f, 0x9d, 0x1b, 0xa3, 0x92, 0xde, 0xc1, 0x6f, 0xd5, 0xfb,
	0x68, 0xa0, 0xf1, 0xf9, 0xeb, 0x01, 0xb9, 0x52, 0xed, 0xda, 0x69, 0xf4, 0x1a, 0x7c, 0x51, 0xb2,
	0x4c, 0xf1, 0x54, 0x5f, 0x06, 0x5e, 0x47, 0xa2, 0x64, 0x69, 0x23, 0x37, 0xb3, 0x1c, 0x6f, 0xcc,
	0xec, 0x64, 0x74, 0x96, 0xe3, 0x8d, 0x9a, 0x6d, 0x92, 0x39, 0x09, 0x74, 0xb2, 0xf3, 0x7f, 0x07,
	0x30, 0x5b, 0xe9, 0xfe, 0x6b, 0xf9, 0x73, 0xdb, 0x7e, 0xf2, 0x0e, 0xee, 0x99, 0x66, 0x92, 0x59,
	0x4b, 0x75, 0x3b, 0x1f, 0x3f, 0x19, 0x9c, 0x9b, 0x85, 0xf7, 0xc8, 0x47, 0x80, 0xbe, 0x99, 0xe4,
	0x69, 0x3b, 0x38, 0x28, 0x76, 0x1c, 0x8f, 0x49, 0x1d, 0xe6, 0x02, 0x8e, 0xda, 0xf2, 0x11, 0xdb,
	0xcd, 0xae, 0x47, 0x1c, 0x0d, 0x85, 0x0e, 0xf0, 0x05, 0x8e, 0xed, 0xa2, 0x91, 0x33, 0xd7, 0xce,
	0xe9, 0x6f, 0xfc, 0x6c, 0x5c, 0xec, 0x60, 0x97, 0x10, 0x58, 0x35, 0x22, 0xb7, 0xa2, 0x3b, 0x99,
	0xce, 0x46, 0xb5, 0x11, 0x52, 0x73, 0x1d, 0x03, 0x92, 0xd5, 0x92, 0x01, 0xc9, 0x69, 0x96, 0x22,
	0x59, 0x17, 0xdb, 0x93, 0x86, 0x7d, 0xeb, 0x49, 0x23, 0x4d, 0x48, 0xf6, 0x7e, 0x4c, 0xd5, 0x5f,
	0xdb, 0xdb, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x97, 0xe9, 0x0e, 0x11, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DynamicUpdateInterfaceClient is the client API for DynamicUpdateInterface service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DynamicUpdateInterfaceClient interface {
	AddZone(ctx context.Context, in *AddZoneRequest, opts ...grpc.CallOption) (*AddZoneResponse, error)
	DeleteZone(ctx context.Context, in *DeleteZoneRequest, opts ...grpc.CallOption) (*DeleteZoneResponse, error)
	AddRRset(ctx context.Context, in *AddRRsetRequest, opts ...grpc.CallOption) (*AddRRsetResponse, error)
	DeleteDomain(ctx context.Context, in *DeleteDomainRequest, opts ...grpc.CallOption) (*DeleteDomainResponse, error)
	DeleteRRset(ctx context.Context, in *DeleteRRsetRequest, opts ...grpc.CallOption) (*DeleteRRsetResponse, error)
	DeleteRdata(ctx context.Context, in *DeleteRdataRequest, opts ...grpc.CallOption) (*DeleteRdataResponse, error)
	UpdateRdata(ctx context.Context, in *UpdateRdataRequest, opts ...grpc.CallOption) (*UpdateRdataResponse, error)
}

type dynamicUpdateInterfaceClient struct {
	cc *grpc.ClientConn
}

func NewDynamicUpdateInterfaceClient(cc *grpc.ClientConn) DynamicUpdateInterfaceClient {
	return &dynamicUpdateInterfaceClient{cc}
}

func (c *dynamicUpdateInterfaceClient) AddZone(ctx context.Context, in *AddZoneRequest, opts ...grpc.CallOption) (*AddZoneResponse, error) {
	out := new(AddZoneResponse)
	err := c.cc.Invoke(ctx, "/client.DynamicUpdateInterface/AddZone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicUpdateInterfaceClient) DeleteZone(ctx context.Context, in *DeleteZoneRequest, opts ...grpc.CallOption) (*DeleteZoneResponse, error) {
	out := new(DeleteZoneResponse)
	err := c.cc.Invoke(ctx, "/client.DynamicUpdateInterface/DeleteZone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicUpdateInterfaceClient) AddRRset(ctx context.Context, in *AddRRsetRequest, opts ...grpc.CallOption) (*AddRRsetResponse, error) {
	out := new(AddRRsetResponse)
	err := c.cc.Invoke(ctx, "/client.DynamicUpdateInterface/AddRRset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicUpdateInterfaceClient) DeleteDomain(ctx context.Context, in *DeleteDomainRequest, opts ...grpc.CallOption) (*DeleteDomainResponse, error) {
	out := new(DeleteDomainResponse)
	err := c.cc.Invoke(ctx, "/client.DynamicUpdateInterface/DeleteDomain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicUpdateInterfaceClient) DeleteRRset(ctx context.Context, in *DeleteRRsetRequest, opts ...grpc.CallOption) (*DeleteRRsetResponse, error) {
	out := new(DeleteRRsetResponse)
	err := c.cc.Invoke(ctx, "/client.DynamicUpdateInterface/DeleteRRset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicUpdateInterfaceClient) DeleteRdata(ctx context.Context, in *DeleteRdataRequest, opts ...grpc.CallOption) (*DeleteRdataResponse, error) {
	out := new(DeleteRdataResponse)
	err := c.cc.Invoke(ctx, "/client.DynamicUpdateInterface/DeleteRdata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicUpdateInterfaceClient) UpdateRdata(ctx context.Context, in *UpdateRdataRequest, opts ...grpc.CallOption) (*UpdateRdataResponse, error) {
	out := new(UpdateRdataResponse)
	err := c.cc.Invoke(ctx, "/client.DynamicUpdateInterface/UpdateRdata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DynamicUpdateInterfaceServer is the server API for DynamicUpdateInterface service.
type DynamicUpdateInterfaceServer interface {
	AddZone(context.Context, *AddZoneRequest) (*AddZoneResponse, error)
	DeleteZone(context.Context, *DeleteZoneRequest) (*DeleteZoneResponse, error)
	AddRRset(context.Context, *AddRRsetRequest) (*AddRRsetResponse, error)
	DeleteDomain(context.Context, *DeleteDomainRequest) (*DeleteDomainResponse, error)
	DeleteRRset(context.Context, *DeleteRRsetRequest) (*DeleteRRsetResponse, error)
	DeleteRdata(context.Context, *DeleteRdataRequest) (*DeleteRdataResponse, error)
	UpdateRdata(context.Context, *UpdateRdataRequest) (*UpdateRdataResponse, error)
}

// UnimplementedDynamicUpdateInterfaceServer can be embedded to have forward compatible implementations.
type UnimplementedDynamicUpdateInterfaceServer struct {
}

func (*UnimplementedDynamicUpdateInterfaceServer) AddZone(ctx context.Context, req *AddZoneRequest) (*AddZoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddZone not implemented")
}
func (*UnimplementedDynamicUpdateInterfaceServer) DeleteZone(ctx context.Context, req *DeleteZoneRequest) (*DeleteZoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteZone not implemented")
}
func (*UnimplementedDynamicUpdateInterfaceServer) AddRRset(ctx context.Context, req *AddRRsetRequest) (*AddRRsetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRRset not implemented")
}
func (*UnimplementedDynamicUpdateInterfaceServer) DeleteDomain(ctx context.Context, req *DeleteDomainRequest) (*DeleteDomainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDomain not implemented")
}
func (*UnimplementedDynamicUpdateInterfaceServer) DeleteRRset(ctx context.Context, req *DeleteRRsetRequest) (*DeleteRRsetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRRset not implemented")
}
func (*UnimplementedDynamicUpdateInterfaceServer) DeleteRdata(ctx context.Context, req *DeleteRdataRequest) (*DeleteRdataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRdata not implemented")
}
func (*UnimplementedDynamicUpdateInterfaceServer) UpdateRdata(ctx context.Context, req *UpdateRdataRequest) (*UpdateRdataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRdata not implemented")
}

func RegisterDynamicUpdateInterfaceServer(s *grpc.Server, srv DynamicUpdateInterfaceServer) {
	s.RegisterService(&_DynamicUpdateInterface_serviceDesc, srv)
}

func _DynamicUpdateInterface_AddZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicUpdateInterfaceServer).AddZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.DynamicUpdateInterface/AddZone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicUpdateInterfaceServer).AddZone(ctx, req.(*AddZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicUpdateInterface_DeleteZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicUpdateInterfaceServer).DeleteZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.DynamicUpdateInterface/DeleteZone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicUpdateInterfaceServer).DeleteZone(ctx, req.(*DeleteZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicUpdateInterface_AddRRset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRRsetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicUpdateInterfaceServer).AddRRset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.DynamicUpdateInterface/AddRRset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicUpdateInterfaceServer).AddRRset(ctx, req.(*AddRRsetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicUpdateInterface_DeleteDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicUpdateInterfaceServer).DeleteDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.DynamicUpdateInterface/DeleteDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicUpdateInterfaceServer).DeleteDomain(ctx, req.(*DeleteDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicUpdateInterface_DeleteRRset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRRsetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicUpdateInterfaceServer).DeleteRRset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.DynamicUpdateInterface/DeleteRRset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicUpdateInterfaceServer).DeleteRRset(ctx, req.(*DeleteRRsetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicUpdateInterface_DeleteRdata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRdataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicUpdateInterfaceServer).DeleteRdata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.DynamicUpdateInterface/DeleteRdata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicUpdateInterfaceServer).DeleteRdata(ctx, req.(*DeleteRdataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicUpdateInterface_UpdateRdata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRdataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicUpdateInterfaceServer).UpdateRdata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.DynamicUpdateInterface/UpdateRdata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicUpdateInterfaceServer).UpdateRdata(ctx, req.(*UpdateRdataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DynamicUpdateInterface_serviceDesc = grpc.ServiceDesc{
	ServiceName: "client.DynamicUpdateInterface",
	HandlerType: (*DynamicUpdateInterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddZone",
			Handler:    _DynamicUpdateInterface_AddZone_Handler,
		},
		{
			MethodName: "DeleteZone",
			Handler:    _DynamicUpdateInterface_DeleteZone_Handler,
		},
		{
			MethodName: "AddRRset",
			Handler:    _DynamicUpdateInterface_AddRRset_Handler,
		},
		{
			MethodName: "DeleteDomain",
			Handler:    _DynamicUpdateInterface_DeleteDomain_Handler,
		},
		{
			MethodName: "DeleteRRset",
			Handler:    _DynamicUpdateInterface_DeleteRRset_Handler,
		},
		{
			MethodName: "DeleteRdata",
			Handler:    _DynamicUpdateInterface_DeleteRdata_Handler,
		},
		{
			MethodName: "UpdateRdata",
			Handler:    _DynamicUpdateInterface_UpdateRdata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dynamic_update_interface.proto",
}
